//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuChaiRiZhi_dudao
    {
        public int id { get; set; }
        public string dianming { get; set; }
        public Nullable<System.DateTime> riqi { get; set; }
        public string project { get; set; }
        public string position { get; set; }
        public string miaoshu { get; set; }
        public string zhenggai { get; set; }
        public string xietiao { get; set; }
        public string picname { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string UploaderPhone { get; set; }
        public string DuDaoMingZi { get; set; }
    }
}
