//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuDaoRights
    {
        public int id { get; set; }
        public string DuDaoMingZi { get; set; }
        public string mobile { get; set; }
        public string Password { get; set; }
        public Nullable<bool> HasRights { get; set; }
    }
}
