//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaiMaApp : DbContext
    {
        public HaiMaApp()
            : base("name=HaiMaApp")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuChaiImages> ChuChaiImages { get; set; }
        public virtual DbSet<ChuChaiRiZhi> ChuChaiRiZhi { get; set; }
        public virtual DbSet<DuDaoRights> DuDaoRights { get; set; }
        public virtual DbSet<NewTongXunLu> NewTongXunLu { get; set; }
        public virtual DbSet<PiFuOnChuChai> PiFuOnChuChai { get; set; }
        public virtual DbSet<SuperAdmin> SuperAdmin { get; set; }
        public virtual DbSet<TakePictureUpload> TakePictureUpload { get; set; }
        public virtual DbSet<TongXunLu> TongXunLu { get; set; }
        public virtual DbSet<TongZhi> TongZhi { get; set; }
        public virtual DbSet<ChuChaiRiZhi_dudao> ChuChaiRiZhi_dudao { get; set; }
        public virtual DbSet<TakePictureUpload_dudao> TakePictureUpload_dudao { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<StaffPosition> StaffPosition { get; set; }
        public virtual DbSet<View_SuperviserTripLog> View_SuperviserTripLog { get; set; }
        public virtual DbSet<View_AreaStatisticsTripLog> View_AreaStatisticsTripLog { get; set; }
        public virtual DbSet<View_SuperviserStatisticsTripLog> View_SuperviserStatisticsTripLog { get; set; }
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<View_AreaPhotosStatistics> View_AreaPhotosStatistics { get; set; }
        public virtual DbSet<View_SuperviserPhotosStatistics> View_SuperviserPhotosStatistics { get; set; }
        public virtual DbSet<View_SuperviserUploadPhotos> View_SuperviserUploadPhotos { get; set; }
        public virtual DbSet<PiFuOnPictureUpload> PiFuOnPictureUpload { get; set; }
    }
}
