//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewTongXunLu
    {
        public int id { get; set; }
        public string QuYu { get; set; }
        public string ShengFen { get; set; }
        public string DuDaoMingZi { get; set; }
        public string Mobile { get; set; }
        public string XiaoShouFuWuDian { get; set; }
        public string ZhuanYingGongSiMingCheng { get; set; }
        public string Address { get; set; }
        public string ZongJingLi { get; set; }
        public string ZongJingLiMobile { get; set; }
        public string XiaoShouJingLi { get; set; }
        public string XiaoShouJingLiMobile { get; set; }
        public string ShiChangJingLi { get; set; }
        public string ShiChangJingLiMobile { get; set; }
        public string Password { get; set; }
    }
}
