//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongZhi
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string sender { get; set; }
        public Nullable<bool> IsPublish { get; set; }
    }
}
