//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongXunLu
    {
        public int id { get; set; }
        public string DianMing { get; set; }
        public string username { get; set; }
        public string realname { get; set; }
        public string ZhiWei { get; set; }
        public string BuMen { get; set; }
        public string description { get; set; }
        public string Mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    }
}
