//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SuperviserUploadPhotos
    {
        public int id { get; set; }
        public string dianming { get; set; }
        public string mainproject { get; set; }
        public string childproject { get; set; }
        public Nullable<System.DateTime> riqi { get; set; }
        public string project { get; set; }
        public string position { get; set; }
        public string description { get; set; }
        public string picname { get; set; }
        public Nullable<System.DateTime> uploaddate { get; set; }
        public string UploaderPhone { get; set; }
        public string StaffName { get; set; }
        public string Mobile { get; set; }
    }
}
