//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaiMaApp.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SuperviserPhotosStatistics
    {
        public string Area { get; set; }
        public string StaffName { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> CountLog { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public int ID { get; set; }
    }
}
